-- Detective Conan Website Database Schema
-- Run this in your Supabase SQL Editor

-- 1. CASES TABLE
-- Stores investigation files and episode guides
create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  type text default 'canon', -- 'canon', 'filler', 'movie'
  image text
);

-- Enable RLS
alter table public.cases enable row level security;

-- Allow public read access (any site visitor can view cases)
create policy "Allow public read access for cases"
on public.cases for select
to anon, authenticated, service_role
using (true);


-- 2. CHARACTERS TABLE
-- Stores character profiles
create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text not null,
  image text,
  faction text default 'main' -- 'main', 'fbi', 'organization', 'police'
);

-- Enable RLS
alter table public.characters enable row level security;

-- Allow public read access
create policy "Allow public read access for characters"
on public.characters for select
to anon, authenticated, service_role
using (true);


-- 3. NEWS TABLE
-- Stores news articles, gossip, and updates
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  category text default 'General',
  image text,
  link text
);

-- Enable RLS
alter table public.news enable row level security;

-- Allow public read access
create policy "Allow public read access for news"
on public.news for select
to anon, authenticated, service_role
using (true);

-- NOTE:
-- Insert/Update/Delete operations are performed by the 'service_role' key
-- in your API routes (supabaseAdmin client). Access is restricted by your
-- ADMIN_SECRET and authenticateAdmin function.
