-- Supabase Database Setup for Detective Conan Website
-- Run this in your Supabase SQL Editor

-- Create news table
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  category VARCHAR(50) DEFAULT 'General',
  image TEXT DEFAULT 'assets/hero-bg.png',
  content TEXT NOT NULL,
  link TEXT DEFAULT '#',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create cases table
CREATE TABLE IF NOT EXISTS cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  type VARCHAR(20) DEFAULT 'canon',
  image TEXT DEFAULT 'assets/conan-mystery-hero.png',
  description TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cases_created_at ON cases(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_category ON news(category);
CREATE INDEX IF NOT EXISTS idx_cases_type ON cases(type);

-- Enable Row Level Security (RLS)
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

-- Create policies for public read access
CREATE POLICY "Public read access for news" ON news
  FOR SELECT USING (true);

CREATE POLICY "Public read access for cases" ON cases
  FOR SELECT USING (true);

-- Create policies for admin insert access (service role bypasses RLS)
CREATE POLICY "Admin insert access for news" ON news
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin insert access for cases" ON cases
  FOR INSERT WITH CHECK (true);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Add triggers for updated_at
CREATE TRIGGER update_news_updated_at BEFORE UPDATE ON news
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_cases_updated_at BEFORE UPDATE ON cases
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Insert sample data (optional)
INSERT INTO news (title, category, content) VALUES
  ('New Black Organization Member Revealed!', 'Breaking News', 'Rumors swirl about a new high-ranking member in the Black Organization. Sources suggest this person has been operating in the shadows for years.'),
  ('Detective Conan Movie 28 Breaks Records', 'Merchandise', 'The latest Detective Conan film has surpassed box office expectations, becoming the highest-grossing film in the franchise.'),
  ('Interview with Gosho Aoyama', 'Interview', 'In an exclusive interview, the creator of Detective Conan hints at the series approaching its grand finale.');

INSERT INTO cases (title, type, description) VALUES
  ('The Mystery of the Missing Detective', 'canon', 'Conan must solve the case of a missing private investigator while maintaining his cover.'),
  ('The Black Organization''s Trap', 'anime', 'A complex trap set by the Black Organization tests Conan''s detective skills to their limits.'),
  ('The Million Dollar Pentagram', 'movie', 'Heiji Hattori takes center stage in this thrilling cinematic adventure.');
